export type ValidSkills =
  | "Python"
  | "PyTorch"
  | "TensorFlow"
  | "Pandas"
  | "Keras"
  | "SciKit-Learn"
  | "NumPy"
  | "Matplotlib"
  | "SciPy"
  | "NLTK"
  | "OpenCV"
  | "LLM / NLP"
  | "Hugging Face"
  | "STATA"
  | "Econometrics"
  | "Data Analysis"
  | "Computer Vision"
  | "Generative AI"
  | "Natural Language Processing"
  | "Artificial Intelligence (AI)"
  | "Data Visualization"
  | "Exploratory Data Analysis"
  | "Descriptive Analysis"
  | "Probability Theory"
  | "Statistical Analysis"
  | "LaTeX"
  | "R"
  | "Stata"
  | "Neo4j"
  | "Cloud"
  | "MS Office"
  | "Excel"
  | "MySQL";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "Econometrics"
  | "STATA"
  | "Data Analysis"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "Biomedical"
  | "NLP"
  | "Knowledge Graphs"
  | "3D Modeling";

export type ValidExpType =
  | "Personal Project"
  | "Professional"
  | "Web Dev"
  | "Internship"
  | "Mobile Dev"
  | "Biomedical"
  | "NLP"
  | "Knowledge Graphs";

export type ValidPages =
  | "home"
  | "skills"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
